%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\franc\OneDrive - Politecnico di Bari\Desktop\Risultati\risultati nuovi\DlMacStats.txt
%
% Auto-generated by MATLAB on 06-Oct-2019 09:53:06

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "sizeTb1", "Var9", "Var10", "Var11"];
opts.SelectedVariableNames = "sizeTb1";
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "double", "string", "string", "string"];
opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 9, 10, 11], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 9, 10, 11], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("C:\Users\franc\OneDrive - Politecnico di Bari\Desktop\Risultati\risultati nuovi\DlMacStats.txt", opts);

%% Convert to output type
sizeTb1 = tbl.sizeTb1;

%% Clear temporary variables
clear opts tbl