FROM debian:bookworm
RUN apt update && apt install -y texlive texlive-lang-italian texlive-latex-extra texlive-pictures texlive-fonts-extra inkscape
RUN apt install -y python3-pygments

WORKDIR /workspace
