# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

def build_errmsg(program_name):
    return f'{program_name} is not installed. Please install {program_name} development libraries to build ReportTs component.'

def configure(conf):
  conf.check_cfg(package='libpqxx >= 7.6', args=['--cflags', '--libs'], mandatory=True, errmsg=build_errmsg('libpqxx'))
  conf.check_cfg(package='libpq >= 5.13', args=['--cflags', '--libs'], mandatory=True, errmsg=build_errmsg('libpq'))

def build(bld):
    module = bld.create_ns3_module('report-ts', ['core'])
    module.source = [
            'model/report-ts.cc'
        ]

    #module_test = bld.create_ns3_module_test_library('drone')
    #module_test.source = [
    #    ]

    headers = bld(features='ns3header')
    headers.module = 'report-ts'
    headers.source = [
            'model/report-ts.h'
        ]

    module.use.extend(['LIBPQXX', 'LIBPQ'])

    #if bld.env.ENABLE_EXAMPLES:
    #    bld.recurse('examples')

    # bld.ns3_python_bindings()
