def build(bld):
    obj = bld.create_ns3_program('drone-scenario-allen',
                                 ['drone', 'core', 'network',
                                  'applications', 'mobility', 'wifi',
                                  'internet', 'report'])
    obj.source = 'scenario-allen.cc'

    obj = bld.create_ns3_program('drone-scenario-babbage',
                                 ['drone', 'core', 'network',
                                  'applications', 'mobility', 'wifi',
                                  'internet'])
    obj.source = 'scenario-babbage.cc'

    obj = bld.create_ns3_program('drone-scenario-davinci',
                                 ['drone', 'core', 'network',
                                  'applications', 'mobility', 'wifi',
                                  'internet'])
    obj.source = 'scenario-davinci.cc'

    obj = bld.create_ns3_program('drone-scenario-davinci-threelogdist',
                                 ['drone', 'core', 'network',
                                  'applications', 'mobility', 'wifi',
                                  'internet'])
    obj.source = 'scenario-davinci-threelogdist.cc'

    obj = bld.create_ns3_program('drone-scenario-easley',
                                 ['drone', 'core', 'network',
                                  'applications', 'mobility', 'wifi',
                                  'internet'])
    obj.source = 'scenario-easley.cc'

    obj = bld.create_ns3_program('drone-scenario-easley-threelogdist',
                                 ['drone', 'core', 'network',
                                  'applications', 'mobility', 'wifi',
                                  'internet'])
    obj.source = 'scenario-easley-threelogdist.cc'

    # lte-lena-simple-davinci shouldn't have wifi as dependency,
    # but for some reason there are weak references to it.
    obj = bld.create_ns3_program('lte-lena-simple-davinci',
                                 ['lte', 'drone', 'wifi'])
    obj.source = 'lte-lena-simple-davinci.cc'

    # The following scenarios are strictly dependent on LTE only
    obj = bld.create_ns3_program('lte-lena-costvelocity',
                                 ['lte'])
    obj.source = 'lte-lena-costvelocity.cc'

    obj = bld.create_ns3_program('lte-lena-simple-RWMM',
                                 ['lte'])
    obj.source = 'lte-lena-simple-RWMM.cc'

    obj = bld.create_ns3_program('lte-lena-easley',
                                 ['drone', 'mobility', 'lte', 'wifi'])
    obj.source = 'lte-lena-easley.cc'
