{
 "title": "IoD Sim",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "scenarioId",
    "label": "Scenario ID",
    "query": "SELECT id\nFROM scenario_executions\nWHERE time_end IS NOT NULL\nORDER BY time_start DESC;"
   },
   {
    "name": "droneId",
    "label": "Drone #",
    "query": "SELECT drone_id \nFROM drones_position \nWHERE scenario_id = '$scenarioId'\nORDER BY drone_id;"
   }
  ]
 },
 "panels": [
  {
   "title": "Scenario Executions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  id,\n  name,\n  time_start,\n  time_end\nFROM scenario_executions\nWHERE\n  $__timeFilter(time_start)\n  AND time_end IS NOT NULL\nORDER BY time_start DESC"
    }
   ]
  },
  {
   "title": "Drone Trajectory",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  time_real AS \"time\",\n  drone_id,\n  pos_x AS \"x\",\n  pos_y AS \"y\",\n  pos_z AS \"z\"\nFROM drones_position\nWHERE drone_id IN ($droneId)\nORDER BY time_real"
    }
   ]
  },
  {
   "title": "Drone RSSI",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_real AS \"time\",\n  drone_id,\n  rssi\nFROM wifi_rssi\nWHERE\n  scenario_id = '$scenarioId'\n  AND drone_id IN ($droneId)\nORDER BY 1"
    }
   ]
  }
 ]
}